### ISSUE TITLE
Optimizing Test Duration: Temporarily Ignoring Long-Running Tests with Pytest

### ISSUE THREAD

**Issue by simedroniraluca** [OceanStreamIO/oceanstream#107]
Due to the extended duration of certain tests, we've utilized `@pytest.mark.ignore`. Moving forward, we will need to either refactor these tests or improve the associated functions to reduce their execution time and avoid ignoring them.

**Comment by ruxandra-valcu** [comment]
This applies for the tests in shoal_detection_handler, which take about 3 min each on my machine. Interestingly, the tests in shoal_process, which use the same functionality being tested here, take 30 seconds each. One initial approach had been using pytext fixtures for the prepared dataset, but that only lowered the runtime by a few tens of seconds. Something strange appears to be happening here in the tests rather than the functions themselves....

**Comment by ruxandra-valcu** [comment]
Clearing off for now since we'll entirely rewrite the shoal detection function
